Add straiught forward asynchronous operation for CommandSession
nonebot/nonebot pull request #232
Opened 2020-08-18 17:10 UTC by Hieuzest

CommandSession.aget()
CommandSession.apause()
will pause the session asynchronously and wait till next wakeup

Example Code:

```python
@nonebot.on_command("test")
async def test_command(session: nonebot.CommandSession):
    def validate_digit(x):
        if x in list('0123456789'):
            return int(x)
        else:
            raise ValidateError("???Input a digit:")

    def validate_string(x):
        if len(x) > 5:
            return x
        else:
            raise ValidateError("???Input a string (len > 5):")

    number = await session.aget('number', prompt='Input a digit:', arg_filters=[validate_digit])
    string = await session.aget('str', prompt='Input a string (len > 5):', arg_filters=[validate_string])
    # Do something
    session.finish(f'Get number and string: {number} {string}')

```

2020-08-18 17:30 UTC, mnixry commented on nonebot/command/__init__.py
> +class _YieldException(Exception):
这个Exception是不是应该也从Command Interrupt继承

2020-08-18 17:58 UTC, Hieuzest commented on nonebot/command/__init__.py
> +class _YieldException(Exception):
是的，手快了没继承上去
以及Exception这个话题。。我曾经是把这些都改成BaseException的
不过这里没有任何影响，_YieldException不会进入用户代码。也不可能在用户代码中被抛出

2020-08-18 18:33 UTC, cleoold commented
能敘述一下這個新功能和已經存在的session.{pause|get } 會有什麼顯著的區別嗎？

2020-08-18 18:43 UTC, lengthmin approved these changes
我感觉没有 breaking changes，功能应该是实现了的。
不通过 exception 的方式来重新执行 command，而是异步等待让代码从当前区域向下执行，达到和 pause 同样的效果。
虽然我具体没太懂 [L692-L698](https://github.com/nonebot/nonebot/pull/232/files#diff-bd15d1e7d2523c471ba75cd87b11c287R692-R698) 的原理，但对代码整体感觉没什么问题。

2020-08-18 18:48 UTC, lengthmin commented
> 我个人认为改Exception属于breaking change
> 如果用户又套了一层装饰器处理异常的话可能会出问题

只是多了一个 `_YieldException`，而且只会在用户使用了 `a(get|pause)` 的情况下有该 `_YieldException`，其他情况我暂且认为没什么问题，不会有多余的东西。

2020-08-18 19:58 UTC, Hieuzest commented
> 能敘述一下這個新功能和已經存在的session.{pause|get} 會有什麼顯著的區別嗎？

很多新用户在接触argsparser的时候会有「这个东西怎么pause了要重新从头执行」这样的疑惑
对于命令需要多个参数/多次交互的场合，可能需要手动维护一个状态机来决定每一次进入的执行路径
这是不直观的，使用异步逻辑可以写出更直接的代码，尤其当和循环配合的时候
以及，可以避免对state的直接使用（原本用于在多次执行中维护状态，这里只需要local就可以）

> > 我个人认为改Exception属于breaking change
> > 如果用户又套了一层装饰器处理异常的话可能会出问题
> 
> 只是多了一个 `_YieldException`，而且只会在用户使用了 `a(get|pause)` 的情况下有该 `_YieldException`，其他情况我暂且认为没什么问题，不会有多余的东西。

_YieldException不会暴露，因为跨协程/上下文调用session的pause,finish,switch是没有意义的，而当处于waiting状态时session自身也无法进行任何调用。
raise_的motivation是: 
- 使得L92 L103 两处raise _YieldException
- （逻辑上不应存在，必定导致错误）避免错误的跨协程调用导致session泄露

2020-08-18 21:03 UTC, cleoold commented
我嘗試了一下，的確和原來的 get 有所不同。因爲 OP 沒有給出例子，我來給一個直觀的
```py
@nonebot.on_command('test1')
async def _(session: nonebot.CommandSession):
	await session.send('hello')
	session.get('xxx', prompt='请输入1')
	session.get('xxy', prompt='请输入2')
	session.get('xxz', prompt='请输入3')

@nonebot.on_command('test2')
async def _(session: nonebot.CommandSession):
	await session.send('hello')
	await session.aget('xxx', prompt='请输入1')
	await session.aget('xxy', prompt='请输入2')
	await session.aget('xxz', prompt='请输入3')
```
使用 get 會執行這個函數四次打印四個 'hello'，而使用 aget 僅會順序執行一邊打印一個 'hello'。這是個很好的提升，謝謝大佬的思路！

2020-08-18 21:06 UTC, cleoold commented on nonebot/command/__init__.py
> -
爲了統一性這些空格還沒有必要刪去？

2020-08-18 21:10 UTC, cleoold commented on nonebot/command/__init__.py
> +            self._future = asyncio.Future()
`loop.create_future()`  是官方建議的寫法

2020-08-18 21:12 UTC, cleoold commented on nonebot/command/__init__.py
> +            self._future = asyncio.Future()
`loop.create_future()` 是官方建議的寫法

2020-08-18 21:16 UTC, Hieuzest commented on nonebot/command/__init__.py
> -
这里事实上是我的git自动忽略了这些trailing space，我之后看一下怎么手动改回来

2020-08-18 21:17 UTC, Hieuzest commented
增加了force_update参数，允许key为空。
这里，key为空仅仅意味着获取用户下一次的输入并使用arg_filters处理它
到此为止，事实上aget已经允许了session的二次分发，可以实现在nonebot之下的另一层dispather
可以纯粹由session.aget和session.send来构建应用
简单来讲，Session即应用
举例：
```python
@nonebot.on_command("talk")
async def test_command(session: nonebot.CommandSession):
    process = ...
    while cmd := await session.aget():
        if cmd == 'exit':
            break
        await session.send(process(cmd))

```
接入相应的api，在这个session内（输入exit前）可以完成整个应用
类似的，可以对cmd进行判断从而二次分发
这样做的好处是避免命令的零散化
一个plugin内的命令可以具有高的相关性，这个时候可以在session内进行
相比于CommandGroup，session可以更好的共享状态

2020-08-19 02:13 UTC, richardchien requested changes
再确认一下，这个变化应该不会影响到原来使用 `get` 的 command 吧，还有就是，使用 `aget` 的 command 和旧的 command 可以进行互相 call 和 switch 嘛

如果上面说的没问题的话，希望再补充一下 `api.md`（使用 `<Badge text="master"/>` 标记）和 `changelog.md`（新增一个 `## master` 标题），然后就可以 merge 了

2020-08-19 02:13 UTC, richardchien commented on nonebot/command/__init__.py
> +                   key: str = ...,
这里为什么不用 `Optional[str]` 呢

2020-08-19 02:13 UTC, richardchien commented on nonebot/command/__init__.py
> +                # session.running = True
这个应该是不在这设置了吧，最好把这个注释删掉？

2020-08-19 02:18 UTC, Hieuzest commented on nonebot/command/__init__.py
> +                   key: str = ...,
None就不会触发arg_filters

2020-08-19 02:28 UTC, richardchien commented on nonebot/command/__init__.py
> +                   key: str = ...,
也就是说 `...` 真实地作为 key 了，唔，那就这样吧

2020-08-19 06:32 UTC, Hieuzest commented
修正了对ValidateError的处理

事实上并不存在`新的`和`旧的`的区别，当call/switch时一定在command handler内部，那么command一定不是waiting的，从而新加入的逻辑不会造成影响

2020-08-19 15:11 UTC, merged

2021-01-01 00:57 UTC, cleoold commented
正好提醒我了……
```py
                except _PauseException:
                    continue
```
不好意思應該提前問的，apause() 裡面這個是爲了解決什麽的？

2021-01-01 05:23 UTC, Hieuzest commented
> 正好提醒我了……
> 
> ```python
>                 except _PauseException:
>                     continue
> ```
> 
> 不好意思應該提前問的，apause() 裡面這個是爲了解決什麽的？

raise ValidateError -> pause() -> set_exception(_PauseException()) -> continue
当时好像是不想修改原本的逻辑所以这样写了

2021-10-09 22:10 UTC, cleoold commented
@richardchien please dismiss your review

2021-11-13 13:25 UTC, cleoold commented
> 
> 
> @richardchien please dismiss your review

@richardchien