为on_command装饰器添加同步函数支持
nonebot/nonebot pull request #236
Opened 2020-09-12 03:34 UTC by mnixry

测试用例:
```python
from nonebot import on_command, CommandSession

@on_command('test')
def _(session: CommandSession):
    session.send('Testing!')
    session.finish('Test Finished!')

@on_command('normal_test')
async def _(session: CommandSession):
    await session.send('Normal Testing!')

if __name__ == "__main__":
    import nonebot
    nonebot.init()
    nonebot.run(host='127.0.0.1', port=8080)
```

2020-09-12 22:10 UTC, cleoold reviewed
爲啥改了這麽多格式

2020-09-13 03:27 UTC, mnixry commented
> 爲啥改了這麽多格式

yapf抽风瞎改 不知道为啥

2020-09-13 04:07 UTC, cleoold commented
> 
> 
> > 爲啥改了這麽多格式
> 
> yapf抽风瞎改 不知道为啥

建議弄回去

2020-09-23 01:20 UTC, cleoold requested changes
roll back styles.

2021-02-18 05:48 UTC, cleoold commented
給一個異步庫添置同步的用法其實沒有太大的意義。

在事件循環内創建一個 task 后馬上等待結果像是 antipattern。

如果所有的東西都是同步的話，沒有必要再添加一個事件循環和切換上下文的 overhead。

還是覺得此功能留給使用者自己實現比較好。

2021-02-18 06:13 UTC, closed without merging