OSPP 2021 项目：更新 NoneBot v1 文档中的“指南”部分
nonebot/nonebot pull request #276
Opened 2021-09-06 07:27 UTC by Joeyhey

- 修正了文档中关于 酷Q 和 CQHTTP 的过时内容，使用 go-cqhttp 取代了 酷Q 和 CQHTTP ；
- 修正了 awesome-bot 中不能正确运行的功能，使用腾讯智能对话平台提供的 API 取代图灵机器人，实现智能聊天机器人插件，同时更新了文档中对应部分；
- 修正了 awesome-bot 中的过时内容，使用 aget() 和 apause() 取代 get() 和 pause()。

2021-09-06 10:27 UTC, richardchien requested changes

2021-09-06 10:27 UTC, richardchien commented on docs/guide/code/awesome-bot-3/awesome/plugins/weather/__init__.py
> +        while True:
这段需要测试一下，不太对劲

2021-09-06 10:27 UTC, richardchien commented on docs/guide/code/awesome-bot-4/config.py
> +SECRET_ID = ""
改名叫 `TBP_SECRET_ID` 和 `TBP_SECRET_KEY`

2021-09-08 14:57 UTC, richardchien commented
@cleoold review 一下？

`aget` 和 `apause` @Joeyhey 尝试了一下，发现需要改动现有逻辑，我觉得可以暂时先不动，或者在下一个 PR 再改。

2021-09-10 06:19 UTC, cleoold commented on docs/guide/notice-and-request.md
> +这里首先 `on_request` 装饰器将函数注册为一个请求处理器，`group` 参数表示只处理群请求，这里各请求对应的参数值可以参考 go-cqhttp 帮助中心的 [事件](https://docs.go-cqhttp.org/event/) 的 `request_type` 字段，目前有 `group` 和 `friend` 两种。
```suggestion
这里首先 `on_request` 装饰器将函数注册为一个请求处理器，`group` 参数表示只处理群请求，这里各请求对应的参数值可以参考 go-cqhttp 帮助中心的 [事件](https://docs.go-cqhttp.org/event/) （或 [Onebot 标准](https://github.com/botuniverse/onebot/blob/master/v11/specs/event/request.md)）的 `request_type` 字段，目前有 `group` 和 `friend` 两种。
```

2021-09-10 06:22 UTC, cleoold commented on docs/guide/notice-and-request.md
> +总的来说这些 `on_*` 装饰器用起来都是差不多的，这里的 `group_increase` 表示群成员增加，其它的通知类型可以参考 go-cqhttp 帮助中心的 [事件](https://docs.go-cqhttp.org/event/) 的 `notice_type`。
```suggestion
总的来说这些 `on_*` 装饰器用起来都是差不多的，这里的 `group_increase` 表示群成员增加，其它的通知类型可以参考 go-cqhttp 帮助中心的 [事件](https://docs.go-cqhttp.org/event/) （或 [Onebot 标准](https://github.com/botuniverse/onebot/tree/master/v11/specs/event)）的 `notice_type`。
```

2021-09-10 06:29 UTC, cleoold commented on docs/guide/command.md
> +            await session.pause('要查询的城市名称不能为空呢，请重新输入')
```suggestion
        session.pause('要查询的城市名称不能为空呢，请重新输入')
```

2021-09-10 06:31 UTC, cleoold commented
remember to squash

2021-09-10 06:32 UTC, cleoold commented
> 
> 
> @cleoold review 一下？
> 
> `aget` 和 `apause` @Joeyhey 尝试了一下，发现需要改动现有逻辑，我觉得可以暂时先不动，或者在下一个 PR 再改。

实际上有了 a{get|pause} 之後 arg_parser 就沒有存在的必要了

2021-09-10 07:27 UTC, richardchien commented
> 实际上有了 a{get|pause} 之後 arg_parser 就沒有存在的必要了。aget 要放在 on_command 下面

确实，但 `args_parser` 有个“在第一次进 session 时处理随命令附带的参数”的功能，似乎需要把 `args_parser` 对 `current_arg` 的处理和判断逻辑都搬到 `on_command`

2021-09-12 04:57 UTC, cleoold approved these changes

2021-09-12 08:40 UTC, richardchien approved these changes

2021-09-12 13:41 UTC, richardchien commented
感觉没什么问题的话这个 PR 应该明天可以合并了，`aget` 问题之后再看

2021-09-14 01:52 UTC, merged